on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - '*' # Any tag

name: Upload Release Asset

jobs:
  # https://github.com/actions/upload-release-asset#example-workflow---upload-a-release-asset
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: |
          export TAG=$(echo ${{ github.ref }} | cut -d'/' -f3)
          echo $TAG
          export RELEASE=$(echo $TAG | cut -d'-' -f1)
          echo $RELEASE
          export TARGET=$(echo $TAG | cut -d'-' -f2)
          echo $TARGET
          export SUBTARGET=$(echo $TAG | cut -d'-' -f3)
          echo $SUBTARGET

      # - name: Build project
      #   run: |
      #     make install-deps
      #     make get-builder
      #     make build
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     draft: false
      #     prerelease: false
      # - name: Upload Release Asset
      #   id: upload-release-asset
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./builder/bin/targets/x86/64/openwrt-19.07.7-x86-64-combined-squashfs.img.gz
      #     asset_name: openwrt-19.07.7-x86-64-combined-squashfs.img.gz
      #     asset_content_type: application/gzip
