on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'

name: Create tag, if needed

jobs:
  build:
    name: Create tag, if needed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set vars stage 1
        run: |
          export LATEST_UPSTREAM=$(git -c 'versionsort.suffix=-' ls-remote -q --refs --tags --sort='v:refname' git://git.openwrt.org/openwrt/openwrt.git | cut -d'/' -f3 | tail -n 1)
          echo "latest_upstreamn=${LATEST_UPSTREAM}" >> $GITHUB_ENV
          echo create_tag=$(sh -c "(git -c 'versionsort.suffix=-' ls-remote -q --refs --tags | grep ${LATEST_UPSTREAM}); echo $?") >> $GITHUB_ENV
      - name: Create tag for x86-64
        if: ${{ env.create_tag == '1' }}
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ env.latest_upstream }}-x86-64",
              sha: context.sha
            })
